### ISSUE TITLE
Which LICENSE this repo use?

### ISSUE THREAD

**Issue by junmin-kim** [d21d3q/nanogrpc#1]
Hello!

I'm trying to use nanopb, and I found that this repo supports grpc using nanopb.
If this repo use zlib license like nanopb, how about add the LICENSE file?

Thanks.

**Comment by d21d3q** [comment]
I've just [added](https://github.com/d21d3q/nanogrpc/commit/b910d539cc52586e13a2a45b95963b11a4d81c00) `Unlicense License`
